name: Build and Push Custom Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'


jobs:
  changed-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.modified_directories }}

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: Get changed Dockerfile directories
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: '**/Dockerfile'
          json: true
          dir_names: true

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: changed-images

    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.changed-images.outputs.matrix) }}

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: Set up Image Variables
        id: vars
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.folder }}"
          
          TAG="${{ github.sha }}"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            TAG="latest"
          fi
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_FULL=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_LATEST_FULL=${IMAGE_NAME}:latest" >> $GITHUB_OUTPUT

      - name: ðŸ”‘ Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”¨ Build and Push Docker image for ${{ matrix.folder }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE_FULL }} 
            ${{ steps.vars.outputs.IMAGE_NAME }}:latest
          cache-from: type=gha,scope=${{ matrix.folder }}
          cache-to: type=gha,mode=max,scope=${{ matrix.folder }}
