name: Dynamic Build and Push Custom Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  changed-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ coalesce(steps.changed-files.outputs.modified_directories, '[]') }}


    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Get changed Dockerfile directories
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          base_sha: ${{ github.event.pull_request.base.sha || github.sha }}
          files: '*/Dockerfile'
          json: true
          dir_names: true
          dir_names_max_depth: 1
          files_ignore: '.github/**'


  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs: changed-images

    if: needs.changed-images.outputs.matrix != '[]'

    strategy:
      fail-fast: false
      matrix:
        folder: ${{ fromJson(needs.changed-images.outputs.matrix) }}

    steps:
      - name: â¬‡ï¸ Checkout code
        uses: actions/checkout@v4

      - name: Set up Image Variables
        id: vars
        run: |
          # Formato: ghcr.io/OWNER/REPO/FOLDER
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.folder }}"

          TAG="${{ github.sha }}"
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_name }}" == "main" ]]; then
            TAG="latest"
          fi
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT
          echo "IMAGE_FULL=${IMAGE_NAME}:${TAG}" >> $GITHUB_OUTPUT

      - name: ðŸ”‘ Log in to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ”¨ Build and Push Docker image for ${{ matrix.folder }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.folder }}
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ${{ steps.vars.outputs.IMAGE_FULL }}
            ${{ steps.vars.outputs.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG == 'latest' && 'latest' || '' }}
          cache-from: type=gha,scope=${{ matrix.folder }}
          cache-to: type=gha,mode=max,scope=${{ matrix.folder }}
